/**
 * Query Matrix Generator
 *
 * Generates 100-1000 deterministic query nodes
 * Run at build time: npx tsx scripts/generateQueries.ts
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

interface Query {
  slug: string;
  intent: string;
  type: 'audit' | 'checker' | 'report' | 'analysis' | 'tool';
  seed: string;
  canonical: string;
}

// Core seed queries (must reflect your product capabilities)
const SEEDS = [
  'ai visibility audit',
  'why is my site not indexed by ai',
  'entity seo checker',
  'schema validation ai',
  'citation readiness test',
  'machine readability score',
  'ai answer extraction',
  'visibility in claude ai',
  'visibility in chatgpt',
  'visibility in google ai search',
  'content structuring audit',
  'entity clarity analysis',
  'entity seo competitor comparison',
  'extractability framework',
  'ai crawl audit',
  'semantic html5 validation',
  'structured data audit',
  'json-ld schema audit',
  'open graph metadata audit',
  'microdata validation',
];

// Modifiers (query pattern types)
const MODIFIERS = [
  'tool',
  'checker',
  'report',
  'analysis',
  'audit',
  'guide',
  'framework',
  'best practices',
  'metrics',
];

// Query intent classifications
const INTENT_MAP: Record<string, 'audit' | 'checker' | 'report' | 'analysis' | 'tool'> = {
  tool: 'tool',
  checker: 'checker',
  report: 'report',
  analysis: 'analysis',
  audit: 'audit',
  guide: 'analysis',
  framework: 'audit',
  'best practices': 'audit',
  metrics: 'report',
};

function normalize(s: string): string {
  return s
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '');
}

function generateCanonical(seed: string, modifier: string): string {
  // Generate full canonical URL matching the slug format
  const slug = normalize(`${seed} ${modifier}`);
  return `https://aivis.biz/query/${slug}`;
}

function generateQueries(): Query[] {
  const queries: Query[] = [];
  const seen = new Set<string>();

  for (const seed of SEEDS) {
    for (const modifier of MODIFIERS) {
      const slug = normalize(`${seed} ${modifier}`);

      // Avoid duplicates
      if (seen.has(slug)) continue;
      seen.add(slug);

      const query: Query = {
        slug,
        seed,
        intent: `${seed} ${modifier}`,
        type: (INTENT_MAP[modifier] || 'tool') as any,
        canonical: generateCanonical(seed, modifier),
      };

      queries.push(query);
    }
  }

  // De-duplicate by semantic similarity (remove near-duplicates)
  const deduplicated = deduplicateBySemantic(queries);

  return deduplicated;
}

function deduplicateBySemantic(queries: Query[]): Query[] {
  const grouped: Record<string, Query[]> = {};

  for (const q of queries) {
    const key = q.intent
      .replace(/\s+(audit|report|tool|analysis|checker|guide|framework)/i, '')
      .trim();
    if (!grouped[key]) grouped[key] = [];
    grouped[key].push(q);
  }

  // Keep one variant per semantic group, prefer audit > tool > report > checker
  const priority = { audit: 0, tool: 1, report: 2, analysis: 3, checker: 4 };
  const result: Query[] = [];

  for (const group of Object.values(grouped)) {
    group.sort((a, b) => priority[a.type] - priority[b.type]);
    result.push(group[0]);
  }

  return result;
}

function main() {
  console.log('[QueryGen] Generating query matrix...');

  const queries = generateQueries();
  const outputDir = path.join(__dirname, '../src/generated');
  const outputFile = path.join(outputDir, 'queries.json');

  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write queries.json
  fs.writeFileSync(outputFile, JSON.stringify(queries, null, 2));

  console.log(`[QueryGen] Generated ${queries.length} query nodes`);
  console.log(`[QueryGen] Written to ${outputFile}`);

  // Write TypeScript types
  const typesFile = path.join(outputDir, 'queries.d.ts');
  fs.writeFileSync(
    typesFile,
    `export interface Query {
  slug: string;
  intent: string;
  type: 'audit' | 'checker' | 'report' | 'analysis' | 'tool';
  seed: string;
  canonical: string;
}

export declare const queries: Query[];
`
  );

  // Write index file
  const indexFile = path.join(outputDir, 'index.ts');
  fs.writeFileSync(
    indexFile,
    `// Auto-generated by scripts/generateQueries.ts
export * from './queries.d.js';
export { default as queries } from './queries.json' assert { type: 'json' };
`
  );

  console.log('[QueryGen] Complete');
}

main();
