import React, { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { AlertCircle, ExternalLink, FileText, Loader2, Lock, ShieldCheck } from 'lucide-react';
import type { AnalysisResponse } from '@shared/types';

import { API_URL } from '../config';
import { usePageMeta } from '../hooks/usePageMeta';
import { toSafeHref } from '../utils/safeHref';
import AuditReportCard from '../components/AuditReportCard';
import { RecommendationList } from '../components/RecommendationList';
import PlatformProofLoopCard from '../components/PlatformProofLoopCard';
import TextSummaryView from '../components/TextSummaryView';

interface PublicAuditResponse {
  id: string;
  url: string;
  visibility_score: number;
  created_at: string;
  result: AnalysisResponse;
  is_public_share: true;
  redacted?: boolean;
  redaction_note?: string | null;
  analysis_tier?: string;
  analysis_tier_display?: string;
}

export default function PublicReportPage() {
  const { token } = useParams<{ token: string }>();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [audit, setAudit] = useState<PublicAuditResponse | null>(null);
  const [apiSource, setApiSource] = useState<'same-origin' | 'configured-fallback' | null>(null);

  const pageMeta = useMemo(() => {
    const basePath = token ? `/report/public/${token}` : '/report/public';
    if (audit) {
      let domain: string;
      try { domain = new URL(audit.url).hostname; } catch { domain = audit.url; }
      return {
        title: `Report: ${domain} — Score ${audit.visibility_score}`,
        description: `AI Visibility audit for ${domain} — scored ${audit.visibility_score}/100 on ${new Date(audit.created_at).toLocaleDateString()}.`,
        path: basePath,
        ogTitle: `AI Visibility Report: ${domain} — ${audit.visibility_score}/100`,
        ogDescription: `Evidence-backed AI visibility audit for ${domain}, generated by AiVIS.`,
      };
    }
    return {
      title: 'Shared Report',
      description: 'View a shared historical AI visibility audit report generated by AiVIS.',
      path: basePath,
      ogTitle: 'Shared AI Visibility Report',
    };
  }, [audit, token]);

  usePageMeta(pageMeta);

  useEffect(() => {
    if (!token) {
      setError('Missing report token');
      setLoading(false);
      return;
    }

    const controller = new AbortController();

    (async () => {
      try {
        setLoading(true);
        setError(null);

        const tokenPath = `/api/public/audits/${encodeURIComponent(token)}`;
        const candidates = [
          tokenPath,
          `${API_URL}${tokenPath}`,
        ].filter((value, index, arr) => arr.indexOf(value) === index);

        let lastError = 'Failed to load shared report';
        for (const endpoint of candidates) {
          const res = await fetch(endpoint, { signal: controller.signal });
          const contentType = String(res.headers.get('content-type') || '').toLowerCase();
          if (!res.ok) {
            if (contentType.includes('application/json')) {
              const payload = await res.json().catch(() => ({}));
              lastError = payload?.error || `Could not load shared report (${res.status})`;
            } else {
              lastError = `Could not load shared report (${res.status})`;
            }
            continue;
          }

          if (!contentType.includes('application/json')) {
            lastError = 'Shared report endpoint returned non-JSON content';
            continue;
          }

          const data = (await res.json()) as PublicAuditResponse;
          if (data?.result) {
            setApiSource(endpoint === tokenPath ? 'same-origin' : 'configured-fallback');
            setAudit(data);
            return;
          }
          lastError = 'Shared report payload was incomplete';
        }

        throw new Error(lastError);
      } catch (err: any) {
        if (err?.name === 'AbortError') return;
        setError(err?.message || 'Failed to load shared report');
      } finally {
        setLoading(false);
      }
    })();

    return () => controller.abort();
  }, [token]);

  const reportResult = useMemo(() => audit?.result ?? null, [audit]);
  const topBlocker = useMemo(
    () => (reportResult?.recommendations && reportResult.recommendations.length > 0 ? reportResult.recommendations[0]?.title : null),
    [reportResult]
  );
  const competitorScorePreview = useMemo(() => Math.min(100, Math.max(0, (audit?.visibility_score || 0) + 19)), [audit?.visibility_score]);

  return (
    <div className="text-white">
      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-6">
        <header className="rounded-2xl border border-white/10/70 bg-charcoal-deep p-6">
          <div className="flex items-center gap-2 text-[#6A911E] mb-2">
            <FileText className="w-5 h-5" />
            <p className="text-sm font-semibold uppercase tracking-wide">Public Shared Report</p>
          </div>
          <h1 className="text-2xl md:text-3xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-300 to-indigo-400">This site is not being cited by AI</h1>
          <p className="text-white/55 mt-2 text-sm">
            Readable content alone is not enough. AI must trust and select the source.
          </p>
          {audit?.analysis_tier_display && (
            <div className="mt-3 flex items-center gap-2">
              <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold border ${
                audit.redacted
                  ? 'bg-amber-500/10 border-amber-500/25 text-amber-300'
                  : 'bg-emerald-500/10 border-emerald-500/25 text-emerald-400'
              }`}>
                {audit.redacted ? <Lock className="w-3 h-3" /> : <ShieldCheck className="w-3 h-3" />}
                {audit.analysis_tier_display}
              </span>
              <span className="text-xs text-white/45">
                {audit.redacted ? 'Redacted preview — some sections limited' : 'Full audit — all sections included'}
              </span>
            </div>
          )}
          <div className="mt-4 rounded-xl border border-white/10 bg-white/5 p-4">
            <p className="text-sm leading-7 text-white/70">
              Score: <span className="font-semibold text-white">{audit?.visibility_score ?? "—"}</span> · Verdict:{" "}
              <span className="font-semibold text-white">Readable, not citable</span> · Top blocker:{" "}
              <span className="font-semibold text-white">{topBlocker || "Entity clarity and trust structure"}</span>
            </p>
          </div>
        </header>

        {loading && (
          <div className="rounded-2xl border border-white/10 bg-charcoal-deep p-8 flex items-center gap-3 text-white/75">
            <Loader2 className="w-5 h-5 animate-spin text-[#6A911E]" />
            Loading shared report...
          </div>
        )}

        {!loading && error && (
          <div className="rounded-2xl border border-white/10 bg-charcoal p-6">
            <div className="flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-white/80 mt-0.5" />
              <div>
                <p className="text-white/80 font-semibold">Unable to open shared report</p>
                <p className="text-white/80 text-sm mt-1">{error}</p>
              </div>
            </div>
          </div>
        )}

        {!loading && !error && audit && reportResult && (
          <>
            <div className="rounded-2xl border border-white/10 bg-charcoal-deep p-5 text-sm text-white/75 flex flex-col gap-2">
              <p>
                URL:{' '}
                <a
                  href={toSafeHref(audit.url) || undefined}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 text-[#6A911E] hover:text-[#5A8018]"
                >
                  {audit.url}
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
              </p>
              <p>Analyzed: {new Date(audit.created_at).toLocaleString()}</p>
              <p>Visibility Score: <span className="font-semibold text-white">{audit.visibility_score}</span></p>
              {audit.redacted && (
                <div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 mt-1">
                  <div className="flex items-start gap-2">
                    <Lock className="w-4 h-4 text-amber-400 mt-0.5 shrink-0" />
                    <div>
                      <p className="text-sm font-medium text-amber-300">
                        {audit.redaction_note || 'This public snapshot is redacted for Observer tier sharing.'}
                      </p>
                      <p className="text-xs text-white/50 mt-1">
                        Only 3 recommendations shown with limited detail. Upgrade to Alignment or higher for full public reports with all recommendations, implementation guidance, and evidence artifacts.
                      </p>
                      <Link to="/pricing" className="inline-flex items-center gap-1 text-xs text-[#6A911E] hover:text-[#5A8018] mt-2 font-medium">
                        View plans →
                      </Link>
                    </div>
                  </div>
                </div>
              )}
              {apiSource === 'configured-fallback' && (
                <p className="text-xs text-amber-300/90">Report API source: configured fallback endpoint</p>
              )}
            </div>

            <div className="rounded-2xl border border-violet-400/20 bg-violet-500/10 p-5">
              <h2 className="text-lg font-semibold text-white">This site vs competitors</h2>
              <div className="mt-3 grid gap-3 sm:grid-cols-2">
                <div className="rounded-xl border border-white/10 bg-black/20 p-3">
                  <p className="text-xs uppercase tracking-wide text-white/50">This site</p>
                  <p className="text-2xl font-bold text-white mt-1">{audit.visibility_score}</p>
                </div>
                <div className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-3">
                  <p className="text-xs uppercase tracking-wide text-emerald-200">Competitor preview</p>
                  <p className="text-2xl font-bold text-emerald-200 mt-1">{competitorScorePreview}</p>
                </div>
              </div>
              <p className="mt-3 text-sm text-white/75">You can share this report — or fix it and publish the score lift.</p>
            </div>

            <PlatformProofLoopCard
              url={audit.url}
              score={audit.visibility_score}
              title="Turn snapshot into action"
              subtitle="The real platform loop is baseline, fix, validate, and share. Use this URL as the same-target starting point."
            />

            <div className="rounded-2xl border border-cyan-400/25 bg-cyan-500/10 p-5">
              <h3 className="text-lg font-semibold text-white">Want to see if your site is being ignored too?</h3>
              <p className="mt-2 text-sm text-white/75">Run your own audit in under 60 seconds and find what AI cannot verify.</p>
              <div className="mt-3 flex flex-wrap gap-2">
                <Link to="/app/analyze" className="inline-flex items-center gap-1 rounded-xl border border-cyan-300/30 bg-cyan-400/15 px-3 py-2 text-xs font-semibold text-cyan-100 hover:bg-cyan-400/20">
                  Run your audit
                </Link>
                <Link to="/pricing" className="inline-flex items-center gap-1 rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-xs font-semibold text-white/90 hover:bg-white/15">
                  See why they win
                </Link>
              </div>
            </div>

            {reportResult.text_summary && (
              <TextSummaryView
                summary={reportResult.text_summary}
                score={audit.visibility_score}
                url={audit.url}
                isObserver={audit.redacted}
              />
            )}

            <AuditReportCard result={reportResult} hideHero hideGrades />

            {Array.isArray(reportResult.recommendations) && reportResult.recommendations.length > 0 && (
              <div className="space-y-3">
                <h2 className="text-xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-blue-300 to-indigo-400">Recommended Fixes</h2>
                <RecommendationList recommendations={reportResult.recommendations} />
              </div>
            )}

            <AuditReportCard result={reportResult} hideHero hideHighlights />
          </>
        )}

        <div className="pt-3">
          <Link to="/" className="text-sm text-[#6A911E] hover:text-[#5A8018]">Return to AiVIS →</Link>
        </div>
      </main>
    </div>
  );
}
