/**
 * Fix Worker - BullMQ worker that generates patches for audit issues.
 * Reads the issue from DB, generates a fix plan, then enqueues a PR job.
 */
import { Worker } from 'bullmq';
import { getBullMQConnection } from '../infra/queues/connection.js';
import { getPool } from '../services/postgresql.js';
import { enqueuePRJob } from '../infra/queues/prQueue.js';
import type { FixJobData } from '../infra/queues/fixQueue.js';

let workerInstance: Worker<FixJobData> | null = null;

async function processFixJob(data: FixJobData): Promise<void> {
  const pool = getPool();

  // 1. Load issue + evidence
  const { rows: issueRows } = await pool.query(
    `SELECT i.*, e.url AS evidence_url, e.message AS evidence_message, e.raw AS evidence_raw
     FROM v1_issues i
     LEFT JOIN v1_evidence e ON e.issue_id = i.id
     WHERE i.id = $1`,
    [data.issueId]
  );
  if (!issueRows.length) throw new Error(`Issue ${data.issueId} not found`);

  const issue = issueRows[0];

  // 2. Load project repo info
  const { rows: projectRows } = await pool.query(
    `SELECT repo_owner, repo_name, repo_installation_id FROM v1_projects WHERE id = $1 AND org_id = $2`,
    [data.projectId, data.orgId]
  );
  if (!projectRows.length) throw new Error(`Project ${data.projectId} not found`);

  const project = projectRows[0];

  if (!project.repo_owner || !project.repo_name || !project.repo_installation_id) {
    // Mark fix as failed - no repo connected
    await pool.query(
      `UPDATE v1_fixes SET status = 'failed', updated_at = NOW() WHERE id = (
         SELECT id FROM v1_fixes WHERE issue_id = $1 ORDER BY created_at DESC LIMIT 1
       )`,
      [data.issueId]
    );
    throw new Error('Project has no GitHub repo connected');
  }

  // 3. Generate fix content based on issue type
  const fixFiles = generateFixContent(issue);

  if (fixFiles.length === 0) {
    await pool.query(
      `UPDATE v1_fixes SET status = 'skipped', updated_at = NOW() WHERE issue_id = $1 AND status = 'pending'`,
      [data.issueId]
    );
    return;
  }

  // 4. Update fix status to in_progress
  await pool.query(
    `UPDATE v1_fixes SET status = 'in_progress', updated_at = NOW() WHERE issue_id = $1 AND status = 'pending'`,
    [data.issueId]
  );

  // 5. Enqueue PR creation
  await enqueuePRJob({
    fixId: data.issueId, // fix is 1:1 with issue for now
    projectId: data.projectId,
    orgId: data.orgId,
    userId: data.userId,
    repoOwner: project.repo_owner,
    repoName: project.repo_name,
    installationId: Number(project.repo_installation_id),
    baseBranch: 'main',
    files: fixFiles,
    title: `fix(aivis): ${issue.title.slice(0, 60)}`,
    body: buildPRBody(issue, data.expectedDelta),
  });

  // 6. Update fix status
  await pool.query(
    `UPDATE v1_fixes SET status = 'pr_queued', updated_at = NOW() WHERE issue_id = $1 AND status = 'in_progress'`,
    [data.issueId]
  );
}

function generateFixContent(issue: any): Array<{ path: string; content: string; justification: string }> {
  const files: Array<{ path: string; content: string; justification: string }> = [];
  const severity = String(issue.severity || '').toLowerCase();
  const title = String(issue.title || '').toLowerCase();

  // Schema fixes
  if (/schema|json-ld|structured data/i.test(title)) {
    files.push({
      path: 'public/schema.json',
      content: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'WebSite',
        name: 'Your Site',
        description: 'Add your site description',
        url: 'https://yoursite.com',
      }, null, 2),
      justification: `Add structured data to improve AI visibility (severity: ${severity})`,
    });
  }

  // Meta description fixes
  if (/meta description/i.test(title)) {
    files.push({
      path: 'src/components/Head.tsx',
      content: `// Auto-generated meta description component
export function MetaDescription({ description }: { description: string }) {
  return <meta name="description" content={description} />;
}
`,
      justification: `Add meta description component (severity: ${severity})`,
    });
  }

  return files;
}

function buildPRBody(issue: any, expectedDelta: number): string {
  return `## AiVIS AutoFix

**Issue:** ${issue.title}
**Severity:** ${issue.severity}
**Expected Score Impact:** +${expectedDelta} points

### What this PR does
Addresses the identified AI visibility issue automatically.

### Evidence
${issue.evidence_message || 'See audit report for details.'}

---
*Generated by AiVIS AutoFix Engine*
`;
}

export function startFixWorker(): void {
  const connection = getBullMQConnection();
  if (!connection) {
    console.log('[FixWorker] Redis not configured - fix worker disabled');
    return;
  }
  if (workerInstance) return;

  workerInstance = new Worker<FixJobData>('fix', async (job) => {
    console.log(`[FixWorker] Processing fix job ${job.id} for issue ${job.data.issueId}`);
    await processFixJob(job.data);
    console.log(`[FixWorker] Completed fix job ${job.id}`);
  }, {
    connection,
    concurrency: 3,
    limiter: { max: 10, duration: 60_000 },
  });

  workerInstance.on('failed', (job, err) => {
    console.error(`[FixWorker] Job ${job?.id} failed:`, err.message);
  });

  console.log('[FixWorker] Fix worker started');
}
