import React from "react";
import { Link } from "react-router-dom";
import { Database, ArrowRight, Shield, FileSearch, TrendingDown, Terminal } from "lucide-react";
import { usePageMeta } from "../../hooks/usePageMeta";
import PublicPageFrame from "../../components/PublicPageFrame";
import { BRAG_ACRONYM } from "@shared/types";
import { buildWebPageSchema, buildBreadcrumbSchema } from "../../lib/seoSchema";

export default function LedgerIndexPage() {
  usePageMeta({
    title: "Evidence Ledger Index — Cite Ledger Entries",
    description:
      "The Evidence Ledger Index is a machine-crawlable reference of all Cite Ledger entry types: evidence IDs, source URLs, content hashes, and timestamps.",
    path: "/evidence/ledger-index",
    structuredData: [
      buildWebPageSchema({
        name: "Evidence Ledger Index — Cite Ledger Entries",
        description:
          "Machine-crawlable reference of all Cite Ledger entry types, evidence IDs, and traceability structures.",
        path: "/evidence/ledger-index",
      }),
      buildBreadcrumbSchema([
        { name: "Home", path: "/" },
        { name: "About AiVIS", path: "/about-aivis" },
        { name: "Evidence", path: "/evidence/ledger-index" },
        { name: "Ledger Index", path: "/evidence/ledger-index" },
      ]),
    ],
  });

  const entryTypes = [
    {
      label: "Scrape Finding",
      source: "scrape",
      desc: "Emitted when the Puppeteer scraper extracts structural signals: DOM elements, meta tags, schema markup, headings hierarchy, link topology.",
    },
    {
      label: "Evidence Finding",
      source: "evidence",
      desc: "Produced by the evidence extraction stage. Contains validated evidence keys for content depth, readability scores, and authority signals.",
    },
    {
      label: "Rule Finding",
      source: "rules",
      desc: "Generated by the rule engine. Each rule maps to specific evidence keys and produces a pass/fail/warn status with a confidence score.",
    },
    {
      label: "AI Analysis Finding",
      source: "ai_analysis",
      desc: "Output from the AI model pipeline. Contains recommendations, score contributions, and model-specific metadata (model name, token usage).",
    },
    {
      label: "BRAG Gate Finding",
      source: "brag_gate",
      desc: "The BRAG validation gate decision. Records whether the audit passed the hard-guard invariant (no hard blockers with unresolved evidence).",
    },
    {
      label: "Finalize Finding",
      source: "finalize",
      desc: "The terminal entry. Records the final visibility score, recommendation count, and pipeline timing metadata.",
    },
  ];

  return (
    <PublicPageFrame
      icon={Database}
      title="Evidence Ledger Index"
      subtitle="Machine-crawlable reference of all Cite Ledger entry types."
      backTo="/methodology/cite-ledger"
    >
      {/* ─── Purpose ─────────────────────────────────────────────── */}
      <section className="mb-10">
        <p className="text-slate-300 leading-relaxed">
          This page catalogues every entry type recorded in the Cite Ledger. Each entry type
          corresponds to a pipeline stage. All entries share the same structure: sequence number,
          {BRAG_ACRONYM} ID, content hash, previous hash, chain hash, and timestamp. The
          differentiator is the <em>source</em> field, which identifies the originating stage.
        </p>
      </section>

      {/* ─── Entry types ─────────────────────────────────────────── */}
      <section className="mb-10">
        <h2 className="text-2xl font-bold text-white mb-6">Entry Types by Pipeline Stage</h2>
        <div className="space-y-4">
          {entryTypes.map((e) => (
            <div
              key={e.source}
              className="p-4 rounded-lg border border-white/10 hover:border-cyan-500/15 transition-colors"
            >
              <div className="flex items-center gap-3 mb-2">
                <span className="font-mono text-xs text-cyan-400 bg-white/5 px-2 py-0.5 rounded">
                  {e.source}
                </span>
                <h3 className="text-white font-semibold text-sm">{e.label}</h3>
              </div>
              <p className="text-slate-400 text-sm leading-relaxed">{e.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ─── Evidence chain example ──────────────────────────────────── */}
      <section className="mb-10">
        <h2 className="text-xl font-bold text-white mb-4">Evidence Chain Example</h2>
        <div className="bg-slate-900/50 border border-white/10 rounded-lg p-4 font-mono text-xs text-slate-400 space-y-2 overflow-x-auto">
          <div><span className="text-slate-500">seq 0:</span> chain_hash = SHA256(<span className="text-red-400">0000…0000</span> + content_hash_0)</div>
          <div><span className="text-slate-500">seq 1:</span> chain_hash = SHA256(<span className="text-cyan-400">chain_hash_0</span> + content_hash_1)</div>
          <div><span className="text-slate-500">seq 2:</span> chain_hash = SHA256(<span className="text-cyan-400">chain_hash_1</span> + content_hash_2)</div>
          <div className="text-slate-600">…each entry chains to the previous, forming a permanent verifiable sequence.</div>
        </div>
      </section>

      {/* ─── Cross-layer navigation ──────────────────────────────── */}
      <nav className="grid sm:grid-cols-3 gap-4" aria-label="Evidence layer pages">
        <Link to="/evidence/citation-reports" className="p-4 rounded-lg border border-white/10 hover:border-blue-500/30 transition-colors group">
          <FileSearch className="w-4 h-4 text-blue-400 mb-2" />
          <div className="text-sm font-semibold text-white group-hover:text-blue-300 transition-colors">Citation Reports</div>
          <div className="text-xs text-slate-500 mt-1">Where cited, where missing</div>
        </Link>
        <Link to="/evidence/drift-analysis" className="p-4 rounded-lg border border-white/10 hover:border-orange-500/30 transition-colors group">
          <TrendingDown className="w-4 h-4 text-orange-400 mb-2" />
          <div className="text-sm font-semibold text-white group-hover:text-orange-300 transition-colors">Drift Analysis</div>
          <div className="text-xs text-slate-500 mt-1">Attribution stability</div>
        </Link>
        <Link to="/evidence/query-results-log" className="p-4 rounded-lg border border-white/10 hover:border-green-500/30 transition-colors group">
          <Terminal className="w-4 h-4 text-green-400 mb-2" />
          <div className="text-sm font-semibold text-white group-hover:text-green-300 transition-colors">Query Results Log</div>
          <div className="text-xs text-slate-500 mt-1">Raw SERP traces</div>
        </Link>
      </nav>
    </PublicPageFrame>
  );
}
